diff --git a/Makefile b/Makefile
index 9c840c4..dbff6b3 100644
--- a/Makefile
+++ b/Makefile
@@ -52,7 +52,7 @@ scripts: scripts/beesd scripts/beesd@.service
 install_tools: ## Install support tools + libs
 install_tools: src
 	install -Dm755 bin/fiemap $(DESTDIR)$(PREFIX)/bin/fiemap
-	install -Dm755 bin/fiewalk $(DESTDIR)$(PREFIX)/sbin/fiewalk
+	install -Dm755 bin/fiewalk $(DESTDIR)$(PREFIX)/bin/fiewalk

 install_bees: ## Install bees + libs
 install_bees: src $(RUN_INSTALL_TESTS)
@@ -60,7 +60,7 @@ install_bees: src $(RUN_INSTALL_TESTS)

 install_scripts: ## Install scipts
 install_scripts: scripts
-	install -Dm755 scripts/beesd $(DESTDIR)$(PREFIX)/sbin/beesd
+	install -Dm755 scripts/beesd $(DESTDIR)$(PREFIX)/bin/beesd
 	install -Dm644 scripts/beesd.conf.sample $(DESTDIR)/$(ETC_PREFIX)/bees/beesd.conf.sample
 ifneq ($(SYSTEMD_SYSTEM_UNIT_DIR),)
 	install -Dm644 scripts/beesd@.service $(DESTDIR)$(SYSTEMD_SYSTEM_UNIT_DIR)/beesd@.service

